create table host_config (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    connection_mode varchar(32) not null,
    address varchar(255) not null,
    ssh_port integer not null,
    ssh_user varchar(255),
    private_key_path varchar(1024),
    description varchar(2000)
);

create table service_group (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    description varchar(2000)
);

create table monitored_service (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    host_id bigint not null,
    group_id bigint,
    process_match varchar(255) not null,
    restart_command clob not null,
    health_url varchar(1024),
    health_timeout_seconds bigint not null,
    restart_cooldown_seconds bigint not null,
    restart_window_seconds bigint not null,
    max_restarts_in_window integer not null,
    monitoring_enabled boolean not null,
    description varchar(2000),
    constraint fk_monitored_service_host
        foreign key (host_id) references host_config(id),
    constraint fk_monitored_service_group
        foreign key (group_id) references service_group(id)
);

create index idx_monitored_service_host on monitored_service(host_id);
create index idx_monitored_service_group on monitored_service(group_id);
